### ISSUE TITLE
SEGFAULT with namco system 1 board (backtrace) on raspberry pi 3

### ISSUE THREAD

**Issue by dankcushions** [libretro/mame2003-libretro#22]
Seemingly all games using this board segfault in libretro-mame2003 when running on my pi3. Interestingly, the same games work fine on my Mac in this core, or running on the pi3 using libretro-mame2000.

I've tested
splatter.zip (Splatter GHouse)
galaga88.zip (Galaga '88)
pacmania (Pac-Mania)

All produce a backtrace similar to the below:
````
pi@retropie:~/Work $ gdb --args /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame2003/mame2003_libretro.so /home/pi/RetroPie/roms/mame-libretro/pacmania.zip
GNU gdb (Raspbian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/retropie/emulators/retroarch/bin/retroarch...done.
(gdb) tty /dev/tty1
(gdb) dir /home/pi/Work/mame2003-libretro/
Source directories searched: /home/pi/Work/mame2003-libretro:$cdir:$cwd
(gdb) run
Starting program: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame2003/mame2003_libretro.so /home/pi/RetroPie/roms/mame-libretro/pacmania.zip
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x766aa460 (LWP 1272)]
[New Thread 0x75eaa460 (LWP 1273)]
[New Thread 0x719df460 (LWP 1274)]
[New Thread 0x711df460 (LWP 1275)]
[New Thread 0x709df460 (LWP 1276)]
[New Thread 0x701df460 (LWP 1277)]
[New Thread 0x6f77c460 (LWP 1278)]
Program received signal SIGSEGV, Segmentation fault.
0x737f850c in namcos1_paletteram_w (offset=14336, data=0 '\000') at src/vidhrdw/namcos1_vidhrdw.c:176
warning: Source file is more recent than executable.
176		namcos1_paletteram[offset] = data;
(gdb) backtrace
#0  0x737f850c in namcos1_paletteram_w (offset=14336, data=0 '\000') at src/vidhrdw/namcos1_vidhrdw.c:176
#1  0x73d277e8 in WM16 (p=0x74f059f8 <m6809+8>, Addr=38912) at src/cpu/m6809/m6809.c:416
#2  std_ix () at src/cpu/m6809/6809ops.c:2779
#3  0x73d2c274 in m6809_execute (cycles=142) at src/cpu/m6809/m6809.c:936
#4  0x7373b390 in cpunum_execute (cpunum=cpunum@entry=0, cycles=142) at src/cpuintrf.c:1193
#5  0x7373e1b4 in cpu_timeslice () at src/cpuexec.c:621
#6  mame_frame () at src/cpuexec.c:375
#7  0x736d849c in retro_run () at src/libretro/libretro.c:273
#8  0x0001cc5c in core_ctl (state=state@entry=CORE_CTL_RETRO_RUN, data=data@entry=0x0) at libretro_version_1.c:326
#9  0x000268e4 in runloop_iterate (sleep_ms=0x7effe594, sleep_ms@entry=0x7effe58c) at runloop.c:1447
#10 0x0001c230 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:163
#11 0x769dc294 in __libc_start_main (main=0x7efff714, argc=1991249920, argv=0x769dc294 <__libc_start_main+276>, init=<optimized out>, 
    fini=0x10dc48 <__libc_csu_fini>, rtld_fini=0x76fdf408 <_dl_fini>, stack_end=0x7efff714) at libc-start.c:287
#12 0x000199a4 in _start ()
````

One thing I've noticed, is that all of the backtraces have offset set to 14336 at the point of failure. Not sure if that's relevant?

Happy to debug further if anyone has any guidance (I'm a few weeks into playing with C). Thanks!

**Comment by dankcushions** [comment]
Solution! @joolswills recompiled without -O3 optimisations (-O2 instead) and these games work (and possibly others we didn't spot)! see https://github.com/RetroPie/RetroPie-Setup/commit/4015c8bceae2b483baff9b5ff87905c422a3a634

However I suppose to close this issue off we should add a similar fix to the Makefile here as it's currently -O3 for all systems. I know the issue affects pi2 and 3, but it was fine on my Mac before, so perhaps just turning it off for ARM would suffice? Or stop worrying about a few cycles and use O2 for everything :)

**Comment by dankcushions** [comment]
PS, all these games are now working:
4/87 Yokai Douchuuki / Shadowland          NONE H
 6/87 Dragon Spirit (old version)           136  V
??/87 Dragon Spirit (new version)           136  V
 7/87 Blazer                                144  V
 9/87 Quester                               A    V
??/87 Quester (special edition)             A    V
11/87 Pac-Mania                             151  V-FLIP
11/87 Pac-Mania (Japanese version)          151  V
12/87 Galaga '88                            153  V-FLIP
12/87 Galaga '88 (Japanese version)         153  V
 3/88 World Stadium                         154  H
 5/88 Beraboh Man                           B    H
??/88 Beraboh Man (standard NS1 hardware)   NONE H
 7/88 Marchen Maze / Alice In Wonderland    152  H
 8/88 Bakutotsu Kijuutei / Baraduke 2       155  H
10/88 World Court                           143  H
11/88 Splatter House                        181  H
12/88 Face Off                              C    H
 2/89 Rompers                               182  V
 3/89 Blast Off                             183  V
 7/89 World Stadium '89                     184  H
12/89 Dangerous Seed                        308  V
 7/90 World Stadium '90                     310  H
10/90 Pistol Daimyo no Bouken               309  H-FLIP
11/90 Souko Ban Deluxe                      311  H-FLIP
??/90 Puzzle Club (prototype)               ?    V
12/91 Tank Force                            185  H-FLIP
